# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS: 
          - localhost
          - 0.0.0.0
          - 127.0.0.1
          - 192.168.86.74
          - 192.168.86.156
          - 192.168.86.150
          - 192.168.86.151

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true

    Template:
      Count: 4
      SANS:
        - localhost
        - 0.0.0.0
        - 127.0.0.1
        - 192.168.86.74
        - 192.168.86.150
        - 192.168.86.151
        - 192.168.86.156
    Users:
      Count: 1
