version: '2'

volumes:
  orderer.example.com:

networks:
  byfn:
    external:
      name: pi-network

services:

  orderer.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer.example.com
    # environment:
    #   # metrics
    #   # - CORE_METRICS_PROVIDER=prometheus
    #   # - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:8443
    container_name: orderer.example.com
    networks:
    - byfn